var gulp = require('gulp');
var path = require('path');

require('./external/GMXBuilder')(gulp, {
    tempDir: './temp',
    distDir: './dist',
    htmlDistDir: './',
    watchExtensions: ['.js', '.css', '.html', '.less', '.svg']
}, {
    id: 'index',
    htmlfile: './html/index.html',
    components: [{
        id: 'es6-promise',
        bowerComponent: 'git://github.com/jakearchibald/es6-promise.git',
        distFiles: ['dist/es6-promise.js']
    }, {
        bowerComponent: 'jsuri',
        distFiles: ['Uri.js']
    }, {
        bowerComponent: 'jquery',
        distFiles: ['dist/jquery.js']
    }, {
        bowerComponent: 'jquery-ui',
        distFiles: ['jquery-ui.js']
    }, {
        bowerComponent: 'underscore',
        distFiles: ['underscore.js']
    }, {
        bowerComponent: 'backbone',
        distFiles: ['backbone.js']
    }, {
        bowerComponent: 'handlebars',
        distFiles: ['handlebars.js']
    }, {
        id: 'Swiper',
        bowerComponent: 'git://github.com/nolimits4web/Swiper.git',
        distDir: './dist'
    }, {
        id: 'translations',
        srcDir: './external/GMXCommonComponents/Translations',
        build: false
    }, {
        id: 'Utils',
        srcDir: './external/GMXCommonComponents/Utils',
        build: false
    }, {
        id: 'GmxVirtualTileLayer',
        srcDir: './external/GMXCommonComponents/GmxVirtualTileLayer',
        build: false
    }, {
        id: 'FireVirtualLayer',
        srcDir: './external/GMXCommonComponents/FireVirtualLayer',
        distDir: './build',
        build: true
    }, {
        id: 'GmxWidget',
        srcDir: './external/GMXCommonComponents/GmxWidget',
        build: false
    }, {
        id: 'SwitchingCollectionWidget',
        srcDir: './external/GMXCommonComponents/SwitchingCollectionWidget',
        build: false
    }, {
        id: 'CollectionFilterWidget',
        srcDir: './external/GMXCommonComponents/CollectionFilterWidget',
        build: false
    }, {
        id: 'CompositeScrollView',
        srcDir: './external/GMXCommonComponents/CompositeScrollView',
        build: false
    }, {
        srcDir: './external/GMXCommonComponents/CommonStyles',
        id: 'CommonStyles',
        distDir: './build',
        build: true
    }, {
        id: 'ScrollView',
        srcDir: './external/GMXCommonComponents/ScrollView',
        distDir: './build',
        build: true
    }, {
        id: 'LayersDebugger',
        srcDir: './external/GMXCommonComponents/LayersDebugger',
        build: false
    }, {
        id: 'LayersTree',
        srcDir: './external/GMXCommonComponents/LayersTree',
        distDir: './build',
        build: true
    }, {
        id: 'ComponentsManager',
        srcDir: './external/GMXCommonComponents/ComponentsManager',
        distDir: './build',
        build: true
    }, {
        id: 'AnimationHelpers',
        srcDir: './external/GMXCommonComponents/AnimationHelpers',
        build: false
    }, {
        id: 'IconSidebarControl',
        srcDir: './external/GMXCommonComponents/IconSidebarControl',
        build: false
    }, {
        id: 'LayersTreeWidget',
        srcDir: './external/GMXCommonComponents/LayersTreeWidget',
        distDir: './build',
        build: true
    }, {
        id: 'StateManager',
        srcDir: './external/GMXCommonComponents/StateManager',
        build: false
    }, {
        id: 'winnie.core',
        srcDir: './external/winnie-core',
        distDir: './dist',
        build: true
    }, {
        id: 'LayerMarkersCollection',
        srcDir: './external/GMXCommonComponents/LayerMarkersCollection',
        build: false
    }, {
        id: 'MergedCollection',
        srcDir: './components/MergedCollection',
        build: false
    }, {
        id: 'DropdownMenuWidget',
        srcDir: './external/GMXCommonComponents/DropdownMenuWidget',
        distDir: './build',
        build: true
    }, {
        id: 'RadioGroupWidget',
        srcDir: './components/RadioGroupWidget',
        build: false
    }, {
        id: 'CheckboxWidget',
        srcDir: './external/GMXCommonComponents/CheckboxWidget',
        build: false
    }, {
        id: 'MarkerItemView',
        srcDir: './external/GMXCommonComponents/MarkerItemView',
        distDir: './build',
        build: true
    }, {
        id: 'LabelIconWidget',
        srcDir: './external/GMXCommonComponents/LabelIconWidget',
        build: false
    }, {
        id: 'gmxUtils',
        url: 'http://maps.kosmosnimki.ru/api/utilities.js'
    }, {
        id: 'DateInterval',
        srcDir: './external/GMXCommonComponents/DateInterval',
        build: false
    }, {
        id: 'CalendarWidget',
        srcDir: './external/GMXCommonComponents/CalendarWidget',
        distDir: './build',
        build: true
    }, {
        id: 'ModalDialog',
        srcDir: './components/ModalDialog',
        build: false
    }, {
        id: 'AlertsWidget',
        srcDir: './components/AlertsWidget',
        build: false
    }, {
        id: 'MainMenuWidget',
        srcDir: './components/MainMenuWidget',
        distDir: 'build',
        build: true
    }, {
        id: 'Main',
        srcDir: './components/Main',
        distDir: './build',
        build: true
    }, {
        id: 'MobileSectionsMenuWidget',
        srcDir: './components/MobileSectionsMenuWidget',
        build: false
    }]
});
